# ---[ Portable origin rpath
if (APPLE)
  set(CMAKE_MACOSX_RPATH ON)
  set(RPATH_PORTABLE_ORIGIN "@loader_path")
else()
  set(RPATH_PORTABLE_ORIGIN $ORIGIN)
endif()

# ---[ Packages
if (USE_CUDA)
  include(${PROJECT_SOURCE_DIR}/cmake/FindCUDA.cmake)
endif()
if (USE_MLU)
  include(${PROJECT_SOURCE_DIR}/cmake/FindMLU.cmake)
endif()
if (USE_PYTHON_LIBS)
  include(${PROJECT_SOURCE_DIR}/cmake/FindPythonLibs.cmake)
endif()
include(${PROJECT_SOURCE_DIR}/cmake/FindDragon.cmake)

# ---[ Directories
include_directories(${PROJECT_SOURCE_DIR})
include_directories(${DRAGON_INCLUDE_DIR})
if (USE_CUDA)
  include_directories(${CUDA_INCLUDE_DIR})
  include_directories(${THIRD_PARTY_DIR}/cutlass/include)
endif()
if (USE_MLU)
  include_directories(${NEUWARE_INCLUDE_DIR})
endif()

# ---[ Defines
if (USE_CUDA)
  add_definitions(-DUSE_CUDA)
  message(STATUS "Use CUDA.")
endif()
if (USE_MLU)
  add_definitions(-DUSE_MLU)
  message(STATUS "Use MLU.")
endif()
if (USE_PYTHON_LIBS)
  message(STATUS "Use python libraries.")
endif()
if (USE_SHARED_LIBS)
  message(STATUS "Use shared libraries.")
endif()
if (USE_SHARED_CUDA_LIBS)
  message(STATUS "Use shared cuda libraries.")
endif()
